pcl::recognition::RotationSpace Class ReferenceModule Recognition - PointCloudLibrary - W3cubDocs
W3cubDocs
/PointCloudLibrary
This is a class for a discrete representation of the rotation space based on the axis-angle representation.
#include <pcl/recognition/ransac_based/rigid_transform_space.h>
Public Member Functions
RotationSpace (float discretization)
We use the axis-angle representation for rotations.
virtual ~RotationSpace ()
void setCenter (const float *c)
const float * getCenter () const
bool getTransformWithMostVotes (const ModelLibrary::Model *model, float rigid_transform[12]) const
bool addRigidTransform (const ModelLibrary::Model *model, const float axis_angle[3], const float translation[3])
Protected Attributes
CellOctree octree_
RotationSpaceCellCreator cell_creator_
float center_ [3]
Detailed Description
This is a class for a discrete representation of the rotation space based on the axis-angle representation.
This class is not supposed to be very general. That's why it is dependent on the class ModelLibrary.
Author
Chavdar Papazov
Definition at line 194 of file rigid_transform_space.h.
Constructor & Destructor Documentation
RotationSpace()
pcl::recognition::RotationSpace::RotationSpace (float discretization) inline
We use the axis-angle representation for rotations.
The axis is encoded in the vector and the angle is its magnitude. This is represented in an octree with bounds [-pi, pi]^3.
Definition at line 199 of file rigid_transform_space.h.
~RotationSpace()
virtual pcl::recognition::RotationSpace::~RotationSpace () inline virtual
Definition at line 208 of file rigid_transform_space.h.
Member Function Documentation
addRigidTransform()
bool pcl::recognition::RotationSpace::addRigidTransform (const ModelLibrary::Model * model, const float axis_angle[3], const float translation[3]) inline
Definition at line 268 of file rigid_transform_space.h.
getCenter()
const float* pcl::recognition::RotationSpace::getCenter () const inline
Definition at line 222 of file rigid_transform_space.h.
getTransformWithMostVotes()
bool pcl::recognition::RotationSpace::getTransformWithMostVotes (const ModelLibrary::Model * model, float rigid_transform[12]) const inline
Definition at line 225 of file rigid_transform_space.h.
References pcl::recognition::RotationSpaceCell::Entry::computeAverageRigidTransform(), and pcl::recognition::RotationSpaceCell::Entry::getNumberOfTransforms().
setCenter()
void pcl::recognition::RotationSpace::setCenter (const float * c) inline
Definition at line 214 of file rigid_transform_space.h.
Referenced by pcl::recognition::RotationSpaceCreator::create().
Member Data Documentation
cell_creator_
RotationSpaceCellCreator pcl::recognition::RotationSpace::cell_creator_ protected
Definition at line 289 of file rigid_transform_space.h.
center_
float pcl::recognition::RotationSpace::center_[3] protected
Definition at line 290 of file rigid_transform_space.h.
octree_
CellOctree pcl::recognition::RotationSpace::octree_ protected
Definition at line 288 of file rigid_transform_space.h.
The documentation for this class was generated from the following file:
pcl/recognition/ransac_based/rigid_transform_space.h
© 2009–2012, Willow Garage, Inc.
© 2012–, Open Perception, Inc.
Licensed under the BSD License.
https://pointclouds.org/documentation/classpcl_1_1recognition_1_1_rotation_space.html