pcl::recognition::ORROctree::Node::Data Class Reference - PointCloudLibrary - W3cubDocs
W3cubDocs
/PointCloudLibrary
#include <pcl/recognition/ransac_based/orr_octree.h>
Public Member Functions
Data (int id_x, int id_y, int id_z, int lin_id, void *user_data=nullptr)
virtual ~ Data ()
void addToPoint (float x, float y, float z)
void computeAveragePoint ()
void addToNormal (float x, float y, float z)
const float * getPoint () const
float * getPoint ()
const float * getNormal () const
float * getNormal ()
void get3dId (int id[3]) const
int get3dIdX () const
int get3dIdY () const
int get3dIdZ () const
int getLinearId () const
void setUserData (void *user_data)
void * getUserData () const
void insertNeighbor (Node *node)
const std::set< Node * > & getNeighbors () const
Protected Attributes
float n_ [3]
float p_ [3]
int id_x_
int id_y_
int id_z_
int lin_id_
int num_points_
std::set< Node * > neighbors_
void * user_data_
Detailed Description
Definition at line 78 of file orr_octree.h.
Constructor & Destructor Documentation
Data()
pcl::recognition::ORROctree::Node::Data::Data (int id_x, int id_y, int id_z, int lin_id, void * user_data = nullptr) inline
Definition at line 81 of file orr_octree.h.
~ Data()
virtual pcl::recognition::ORROctree::Node::Data::~ Data () inline
Definition at line 92 of file orr_octree.h.
Member Function Documentation
addToNormal()
void pcl::recognition::ORROctree::Node::Data::addToNormal (float x, float y, float z) inline
Definition at line 112 of file orr_octree.h.
addToPoint()
void pcl::recognition::ORROctree::Node::Data::addToPoint (float x, float y, float z) inline
Definition at line 95 of file orr_octree.h.
computeAveragePoint()
void pcl::recognition::ORROctree::Node::Data::computeAveragePoint () inline
Definition at line 102 of file orr_octree.h.
References pcl::recognition::aux::mult3().
get3dId()
void pcl::recognition::ORROctree::Node::Data::get3dId (int id[3]) const inline
Definition at line 127 of file orr_octree.h.
get3dIdX()
int pcl::recognition::ORROctree::Node::Data::get3dIdX () const inline
Definition at line 135 of file orr_octree.h.
get3dIdY()
int pcl::recognition::ORROctree::Node::Data::get3dIdY () const inline
Definition at line 138 of file orr_octree.h.
get3dIdZ()
int pcl::recognition::ORROctree::Node::Data::get3dIdZ () const inline
Definition at line 141 of file orr_octree.h.
Referenced by pcl::recognition::ORROctreeZProjection::Set::compare_nodes_z().
getLinearId()
int pcl::recognition::ORROctree::Node::Data::getLinearId () const inline
Definition at line 144 of file orr_octree.h.
getNeighbors()
const std::set<Node*>& pcl::recognition::ORROctree::Node::Data::getNeighbors () const inline
Definition at line 156 of file orr_octree.h.
getNormal() [1/2]
float* pcl::recognition::ORROctree::Node::Data::getNormal () inline
Definition at line 124 of file orr_octree.h.
getNormal() [2/2]
const float* pcl::recognition::ORROctree::Node::Data::getNormal () const inline
Definition at line 121 of file orr_octree.h.
getPoint() [1/2]
float* pcl::recognition::ORROctree::Node::Data::getPoint () inline
Definition at line 118 of file orr_octree.h.
getPoint() [2/2]
const float* pcl::recognition::ORROctree::Node::Data::getPoint () const inline
Definition at line 115 of file orr_octree.h.
getUserData()
void* pcl::recognition::ORROctree::Node::Data::getUserData () const inline
Definition at line 150 of file orr_octree.h.
insertNeighbor()
void pcl::recognition::ORROctree::Node::Data::insertNeighbor (Node * node) inline
Definition at line 153 of file orr_octree.h.
Referenced by pcl::recognition::ORROctree::Node::makeNeighbors().
setUserData()
void pcl::recognition::ORROctree::Node::Data::setUserData (void * user_data) inline
Definition at line 147 of file orr_octree.h.
Member Data Documentation
id_x_
int pcl::recognition::ORROctree::Node::Data::id_x_ protected
Definition at line 160 of file orr_octree.h.
id_y_
int pcl::recognition::ORROctree::Node::Data::id_y_ protected
Definition at line 160 of file orr_octree.h.
id_z_
int pcl::recognition::ORROctree::Node::Data::id_z_ protected
Definition at line 160 of file orr_octree.h.
lin_id_
int pcl::recognition::ORROctree::Node::Data::lin_id_ protected
Definition at line 160 of file orr_octree.h.
n_
float pcl::recognition::ORROctree::Node::Data::n_[3] protected
Definition at line 159 of file orr_octree.h.
neighbors_
std::set<Node*> pcl::recognition::ORROctree::Node::Data::neighbors_ protected
Definition at line 161 of file orr_octree.h.
num_points_
int pcl::recognition::ORROctree::Node::Data::num_points_ protected
Definition at line 160 of file orr_octree.h.
p_
float pcl::recognition::ORROctree::Node::Data::p_[3] protected
Definition at line 159 of file orr_octree.h.
user_data_
void* pcl::recognition::ORROctree::Node::Data::user_data_ protected
Definition at line 162 of file orr_octree.h.
The documentation for this class was generated from the following file:
pcl/recognition/ransac_based/orr_octree.h
© 2009–2012, Willow Garage, Inc.
© 2012–, Open Perception, Inc.
Licensed under the BSD License.
https://pointclouds.org/documentation/classpcl_1_1recognition_1_1_o_r_r_octree_1_1_node_1_1_data.html