pcl::RSDEstimation - PointCloudLibrary - W3cubDocs
W3cubDocs
/PointCloudLibrary
RSDEstimation estimates the Radius-based Surface Descriptor (minimal and maximal radius of the local surface's curves) for a given point cloud dataset containing points and normals.
#include <pcl/features/rsd.h>
Public Types
using PointCloudOut = typename Feature< PointInT, PointOutT >::PointCloudOut
using PointCloudIn = typename Feature< PointInT, PointOutT >::PointCloudIn
using Ptr = shared_ptr< RSDEstimation< PointInT, PointNT, PointOutT > >
using ConstPtr = shared_ptr< const RSDEstimation< PointInT, PointNT, PointOutT > >
Public Types inherited from pcl::FeatureFromNormals< PointInT, PointNT, PointOutT >
using PointCloudN = pcl::PointCloud< PointNT >
using PointCloudNPtr = typename PointCloudN::Ptr
using PointCloudNConstPtr = typename PointCloudN::ConstPtr
using Ptr = shared_ptr< FeatureFromNormals< PointInT, PointNT, PointOutT > >
using ConstPtr = shared_ptr< const FeatureFromNormals< PointInT, PointNT, PointOutT > >
Public Types inherited from pcl::Feature< PointInT, PointOutT >
using BaseClass = PCLBase< PointInT >
using Ptr = shared_ptr< Feature< PointInT, PointOutT > >
using ConstPtr = shared_ptr< const Feature< PointInT, PointOutT > >
using KdTree = pcl::search::Search< PointInT >
using KdTreePtr = typename KdTree::Ptr
using PointCloudIn = pcl::PointCloud< PointInT >
using PointCloudInPtr = typename PointCloudIn::Ptr
using PointCloudInConstPtr = typename PointCloudIn::ConstPtr
using PointCloudOut = pcl::PointCloud< PointOutT >
using SearchMethod = std::function< int(std::size_t, double, pcl::Indices &, std::vector< float > &)>
using SearchMethodSurface = std::function< int(const PointCloudIn &cloud, std::size_t index, double, pcl::Indices &, std::vector< float > &)>
Public Types inherited from pcl::PCLBase< PointInT >
using PointCloud = pcl::PointCloud< PointInT >
using PointCloudPtr = typename PointCloud::Ptr
using PointCloudConstPtr = typename PointCloud::ConstPtr
using PointIndicesPtr = PointIndices::Ptr
using PointIndicesConstPtr = PointIndices::ConstPtr
Public Member Functions
RSDEstimation ()
Empty constructor.
void setNrSubdivisions (int nr_subdiv)
Set the number of subdivisions for the considered distance interval.
int getNrSubdivisions () const
Get the number of subdivisions for the considered distance interval.
void setPlaneRadius (double plane_radius)
Set the maximum radius, above which everything can be considered planar.
double getPlaneRadius () const
Get the maximum radius, above which everything can be considered planar.
void setKSearch (int)
Disables the setting of the number of k nearest neighbors to use for the feature estimation.
void setSaveHistograms (bool save)
Set whether the full distance-angle histograms should be saved.
bool getSaveHistograms () const
Returns whether the full distance-angle histograms are being saved.
shared_ptr< std::vector< Eigen::MatrixXf, Eigen::aligned_allocator< Eigen::MatrixXf > > > getHistograms () const
Returns a pointer to the list of full distance-angle histograms for all points.
Public Member Functions inherited from pcl::FeatureFromNormals< PointInT, PointNT, PointOutT >
FeatureFromNormals ()
Empty constructor.
virtual ~FeatureFromNormals ()
Empty destructor.
void setInputNormals (const PointCloudNConstPtr &normals)
Provide a pointer to the input dataset that contains the point normals of the XYZ dataset.
PointCloudNConstPtr getInputNormals () const
Get a pointer to the normals of the input XYZ point cloud dataset.
Public Member Functions inherited from pcl::Feature< PointInT, PointOutT >
Feature ()
Empty constructor.
virtual ~Feature ()
Empty destructor.
void setSearchSurface (const PointCloudInConstPtr &cloud)
Provide a pointer to a dataset to add additional information to estimate the features for every point in the input dataset.
PointCloudInConstPtr getSearchSurface () const
Get a pointer to the surface point cloud dataset.
void setSearchMethod (const KdTreePtr &tree)
Provide a pointer to the search object.
KdTreePtr getSearchMethod () const
Get a pointer to the search method used.
double getSearchParameter () const
Get the internal search parameter.
void setKSearch (int k)
Set the number of k nearest neighbors to use for the feature estimation.
int getKSearch () const
get the number of k nearest neighbors used for the feature estimation.
void setRadiusSearch (double radius)
Set the sphere radius that is to be used for determining the nearest neighbors used for the feature estimation.
double getRadiusSearch () const
Get the sphere radius used for determining the neighbors.
void compute (PointCloudOut &output)
Base method for feature estimation for all points given in <setInputCloud (), setIndices ()> using the surface in setSearchSurface () and the spatial locator in setSearchMethod ()
Public Member Functions inherited from pcl::PCLBase< PointInT >
PCLBase ()
Empty constructor.
PCLBase (const PCLBase &base)
Copy constructor.
virtual ~PCLBase ()=default
Destructor.
virtual void setInputCloud (const PointCloudConstPtr &cloud)
Provide a pointer to the input dataset.
const PointCloudConstPtr getInputCloud () const
Get a pointer to the input point cloud dataset.
virtual void setIndices (const IndicesPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
virtual void setIndices (const IndicesConstPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
virtual void setIndices (const PointIndicesConstPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
virtual void setIndices (std::size_t row_start, std::size_t col_start, std::size_t nb_rows, std::size_t nb_cols)
Set the indices for the points laying within an interest region of the point cloud.
IndicesPtr getIndices ()
Get a pointer to the vector of indices used.
const IndicesConstPtr getIndices () const
Get a pointer to the vector of indices used.
const PointInT & operator[] (std::size_t pos) const
Override PointCloud operator[] to shorten code.
Protected Member Functions
void computeFeature (PointCloudOut &output) override
Estimate the estimates the Radius-based Surface Descriptor (RSD) at a set of points given by <setInputCloud (), setIndices ()> using the surface in setSearchSurface () and the spatial locator in setSearchMethod ()
Protected Member Functions inherited from pcl::FeatureFromNormals< PointInT, PointNT, PointOutT >
virtual bool initCompute ()
This method should get called before starting the actual computation.
Protected Member Functions inherited from pcl::Feature< PointInT, PointOutT >
const std::string & getClassName () const
Get a string representation of the name of this class.
virtual bool deinitCompute ()
This method should get called after ending the actual computation.
int searchForNeighbors (std::size_t index, double parameter, pcl::Indices &indices, std::vector< float > &distances) const
Search for k-nearest neighbors using the spatial locator from setSearchmethod, and the given surface from setSearchSurface.
int searchForNeighbors (const PointCloudIn &cloud, std::size_t index, double parameter, pcl::Indices &indices, std::vector< float > &distances) const
Search for k-nearest neighbors using the spatial locator from setSearchmethod, and the given surface from setSearchSurface.
Protected Member Functions inherited from pcl::PCLBase< PointInT >
bool initCompute ()
This method should get called before starting the actual computation.
bool deinitCompute ()
This method should get called after finishing the actual computation.
Protected Attributes
shared_ptr< std::vector< Eigen::MatrixXf, Eigen::aligned_allocator< Eigen::MatrixXf > > > histograms_
The list of full distance-angle histograms for all points.
Protected Attributes inherited from pcl::FeatureFromNormals< PointInT, PointNT, PointOutT >
PointCloudNConstPtr normals_
A pointer to the input dataset that contains the point normals of the XYZ dataset.
Protected Attributes inherited from pcl::Feature< PointInT, PointOutT >
std::string feature_name_
The feature name.
SearchMethodSurface search_method_surface_
The search method template for points.
PointCloudInConstPtr surface_
An input point cloud describing the surface that is to be used for nearest neighbors estimation.
KdTreePtr tree_
A pointer to the spatial search object.
double search_parameter_
The actual search parameter (from either search_radius_ or k_).
double search_radius_
The nearest neighbors search radius for each point.
int k_
The number of K nearest neighbors to use for each point.
bool fake_surface_
If no surface is given, we use the input PointCloud as the surface.
Protected Attributes inherited from pcl::PCLBase< PointInT >
PointCloudConstPtr input_
The input point cloud dataset.
IndicesPtr indices_
A pointer to the vector of point indices to use.
bool use_indices_
Set to true if point indices are used.
bool fake_indices_
If no set of indices are given, we construct a set of fake indices that mimic the input PointCloud.
Detailed Description
template<typename PointInT, typename PointNT, typename PointOutT>
class pcl::RSDEstimation< PointInT, PointNT, PointOutT >
RSDEstimation estimates the Radius-based Surface Descriptor (minimal and maximal radius of the local surface's curves) for a given point cloud dataset containing points and normals.
Note
If you use this code in any academic work, please cite:
Z.C. Marton , D. Pangercic , N. Blodow , J. Kleinehellefort, M. Beetz General 3D Modelling of Novel Objects from a Single View In Proceedings of the 2010 IEEE/RSJ International Conference on Intelligent Robots and Systems (IROS) Taipei, Taiwan, October 18-22, 2010
Z.C. Marton, D. Pangercic, N. Blodow, Michael Beetz. Combined 2D-3D Categorization and Classification for Multimodal Perception Systems. In The International Journal of Robotics Research, Sage Publications pages 13781402, Volume 30, Number 11, September 2011.
Note
The code is stateful as we do not expect this class to be multicore parallelized.
Author
Zoltan-Csaba Marton
Definition at line 131 of file rsd.h.
Member Typedef Documentation
ConstPtr
template<typename PointInT , typename PointNT , typename PointOutT > using pcl::RSDEstimation< PointInT, PointNT, PointOutT >::ConstPtr = shared_ptr<const RSDEstimation<PointInT, PointNT, PointOutT> >
Definition at line 146 of file rsd.h.
PointCloudIn
template<typename PointInT , typename PointNT , typename PointOutT > using pcl::RSDEstimation< PointInT, PointNT, PointOutT >::PointCloudIn = typename Feature<PointInT, PointOutT>::PointCloudIn
Definition at line 143 of file rsd.h.
PointCloudOut
template<typename PointInT , typename PointNT , typename PointOutT > using pcl::RSDEstimation< PointInT, PointNT, PointOutT >::PointCloudOut = typename Feature<PointInT, PointOutT>::PointCloudOut
Definition at line 142 of file rsd.h.
Ptr
template<typename PointInT , typename PointNT , typename PointOutT > using pcl::RSDEstimation< PointInT, PointNT, PointOutT >::Ptr = shared_ptr<RSDEstimation<PointInT, PointNT, PointOutT> >
Definition at line 145 of file rsd.h.
Constructor & Destructor Documentation
RSDEstimation()
template<typename PointInT , typename PointNT , typename PointOutT > pcl::RSDEstimation< PointInT, PointNT, PointOutT >::RSDEstimation () inline
Empty constructor.
Definition at line 150 of file rsd.h.
References pcl::Feature< PointInT, PointOutT >::feature_name_.
Member Function Documentation
computeFeature()
template<typename PointInT , typename PointNT , typename PointOutT > void pcl::RSDEstimation< PointInT, PointNT, PointOutT >::computeFeature (PointCloudOut & output) override protected virtual
Estimate the estimates the Radius-based Surface Descriptor (RSD) at a set of points given by <setInputCloud (), setIndices ()> using the surface in setSearchSurface () and the spatial locator in setSearchMethod ()
Parameters
output the resultant point cloud model dataset that contains the RSD feature estimates (r_min and r_max values)
Implements pcl::Feature< PointInT, PointOutT >.
Definition at line 248 of file rsd.hpp.
References pcl::PointCloud< PointT >::clear(), pcl::computeRSD(), pcl::PointCloud< PointT >::height, pcl::PointCloud< PointT >::size(), and pcl::PointCloud< PointT >::width.
getHistograms()
template<typename PointInT , typename PointNT , typename PointOutT > shared_ptr<std::vector<Eigen::MatrixXf, Eigen::aligned_allocator<Eigen::MatrixXf> > > pcl::RSDEstimation< PointInT, PointNT, PointOutT >::getHistograms () const inline
Returns a pointer to the list of full distance-angle histograms for all points.
Returns
the histogram being saved when computing RSD
Definition at line 205 of file rsd.h.
References pcl::RSDEstimation< PointInT, PointNT, PointOutT >::histograms_.
getNrSubdivisions()
template<typename PointInT , typename PointNT , typename PointOutT > int pcl::RSDEstimation< PointInT, PointNT, PointOutT >::getNrSubdivisions () const inline
Get the number of subdivisions for the considered distance interval.
Returns
the number of subdivisions
Definition at line 165 of file rsd.h.
getPlaneRadius()
template<typename PointInT , typename PointNT , typename PointOutT > double pcl::RSDEstimation< PointInT, PointNT, PointOutT >::getPlaneRadius () const inline
Get the maximum radius, above which everything can be considered planar.
Returns
the plane_radius used
Definition at line 179 of file rsd.h.
getSaveHistograms()
template<typename PointInT , typename PointNT , typename PointOutT > bool pcl::RSDEstimation< PointInT, PointNT, PointOutT >::getSaveHistograms () const inline
Returns whether the full distance-angle histograms are being saved.
Returns
true if the histograms are being be saved
Definition at line 199 of file rsd.h.
setKSearch()
template<typename PointInT , typename PointNT , typename PointOutT > void pcl::RSDEstimation< PointInT, PointNT, PointOutT >::setKSearch (int) inline
Disables the setting of the number of k nearest neighbors to use for the feature estimation.
Definition at line 183 of file rsd.h.
References pcl::Feature< PointInT, PointOutT >::getClassName().
setNrSubdivisions()
template<typename PointInT , typename PointNT , typename PointOutT > void pcl::RSDEstimation< PointInT, PointNT, PointOutT >::setNrSubdivisions (int nr_subdiv) inline
Set the number of subdivisions for the considered distance interval.
Parameters
[in] nr_subdiv the number of subdivisions
Definition at line 159 of file rsd.h.
Referenced by pcl::GRSDEstimation< PointInT, PointNT, PointOutT >::computeFeature().
setPlaneRadius()
template<typename PointInT , typename PointNT , typename PointOutT > void pcl::RSDEstimation< PointInT, PointNT, PointOutT >::setPlaneRadius (double plane_radius) inline
Set the maximum radius, above which everything can be considered planar.
Note
the order of magnitude should be around 10-20 times the search radius (0.2 works well for typical datasets).
on accurate 3D data (e.g. openni sernsors) a search radius as low as 0.01 still gives good results.
Parameters
[in] plane_radius the new plane radius
Definition at line 173 of file rsd.h.
Referenced by pcl::GRSDEstimation< PointInT, PointNT, PointOutT >::computeFeature().
setSaveHistograms()
template<typename PointInT , typename PointNT , typename PointOutT > void pcl::RSDEstimation< PointInT, PointNT, PointOutT >::setSaveHistograms (bool save) inline
Set whether the full distance-angle histograms should be saved.
Note
Obtain the list of histograms by getHistograms ()
Parameters
[in] save set to true if histograms should be saved
Definition at line 193 of file rsd.h.
References pcl::io::save().
Member Data Documentation
histograms_
template<typename PointInT , typename PointNT , typename PointOutT > shared_ptr<std::vector<Eigen::MatrixXf, Eigen::aligned_allocator<Eigen::MatrixXf> > > pcl::RSDEstimation< PointInT, PointNT, PointOutT >::histograms_ protected
The list of full distance-angle histograms for all points.
Definition at line 218 of file rsd.h.
Referenced by pcl::RSDEstimation< PointInT, PointNT, PointOutT >::getHistograms().
The documentation for this class was generated from the following files:
pcl/features/rsd.h
pcl/features/impl/rsd.hpp
20092012, Willow Garage, Inc.
2012, Open Perception, Inc.
Licensed under the BSD License.
https://pointclouds.org/documentation/classpcl_1_1_r_s_d_estimation.html