pcl::SampleConsensusModelPlane - PointCloudLibrary - W3cubDocs
W3cubDocs
/PointCloudLibrary
SampleConsensusModelPlane defines a model for 3D plane segmentation.
#include <pcl/sample_consensus/sac_model_plane.h>
Public Types
using PointCloud = typename SampleConsensusModel< PointT >::PointCloud
using PointCloudPtr = typename SampleConsensusModel< PointT >::PointCloudPtr
using PointCloudConstPtr = typename SampleConsensusModel< PointT >::PointCloudConstPtr
using Ptr = shared_ptr< SampleConsensusModelPlane< PointT > >
using ConstPtr = shared_ptr< const SampleConsensusModelPlane< PointT > >
Public Types inherited from pcl::SampleConsensusModel< PointT >
using PointCloud = pcl::PointCloud< PointT >
using PointCloudConstPtr = typename PointCloud::ConstPtr
using PointCloudPtr = typename PointCloud::Ptr
using SearchPtr = typename pcl::search::Search< PointT >::Ptr
using Ptr = shared_ptr< SampleConsensusModel< PointT > >
using ConstPtr = shared_ptr< const SampleConsensusModel< PointT > >
Public Member Functions
SampleConsensusModelPlane (const PointCloudConstPtr &cloud, bool random=false)
Constructor for base SampleConsensusModelPlane.
SampleConsensusModelPlane (const PointCloudConstPtr &cloud, const Indices &indices, bool random=false)
Constructor for base SampleConsensusModelPlane.
~SampleConsensusModelPlane ()
Empty destructor.
bool computeModelCoefficients (const Indices &samples, Eigen::VectorXf &model_coefficients) const override
Check whether the given index samples can form a valid plane model, compute the model coefficients from these samples and store them internally in model_coefficients_.
void getDistancesToModel (const Eigen::VectorXf &model_coefficients, std::vector< double > &distances) const override
Compute all distances from the cloud data to a given plane model.
void selectWithinDistance (const Eigen::VectorXf &model_coefficients, const double threshold, Indices &inliers) override
Select all the points which respect the given model coefficients as inliers.
std::size_t countWithinDistance (const Eigen::VectorXf &model_coefficients, const double threshold) const override
Count all the points which respect the given model coefficients as inliers.
void optimizeModelCoefficients (const Indices &inliers, const Eigen::VectorXf &model_coefficients, Eigen::VectorXf &optimized_coefficients) const override
Recompute the plane coefficients using the given inlier set and return them to the user.
void projectPoints (const Indices &inliers, const Eigen::VectorXf &model_coefficients, PointCloud &projected_points, bool copy_data_fields=true) const override
Create a new point cloud with inliers projected onto the plane model.
bool doSamplesVerifyModel (const std::set< index_t > &indices, const Eigen::VectorXf &model_coefficients, const double threshold) const override
Verify whether a subset of indices verifies the given plane model coefficients.
pcl::SacModel getModelType () const override
Return a unique id for this model (SACMODEL_PLANE).
Public Member Functions inherited from pcl::SampleConsensusModel< PointT >
SampleConsensusModel (const PointCloudConstPtr &cloud, bool random=false)
Constructor for base SampleConsensusModel.
SampleConsensusModel (const PointCloudConstPtr &cloud, const Indices &indices, bool random=false)
Constructor for base SampleConsensusModel.
virtual ~SampleConsensusModel ()
Destructor for base SampleConsensusModel.
virtual void getSamples (int &iterations, Indices &samples)
Get a set of random data samples and return them as point indices.
virtual void setInputCloud (const PointCloudConstPtr &cloud)
Provide a pointer to the input dataset.
PointCloudConstPtr getInputCloud () const
Get a pointer to the input point cloud dataset.
void setIndices (const IndicesPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
void setIndices (const Indices &indices)
Provide the vector of indices that represents the input data.
IndicesPtr getIndices () const
Get a pointer to the vector of indices used.
const std::string & getClassName () const
Get a string representation of the name of this class.
unsigned int getSampleSize () const
Return the size of a sample from which the model is computed.
unsigned int getModelSize () const
Return the number of coefficients in the model.
void setRadiusLimits (const double &min_radius, const double &max_radius)
Set the minimum and maximum allowable radius limits for the model (applicable to models that estimate a radius)
void getRadiusLimits (double &min_radius, double &max_radius) const
Get the minimum and maximum allowable radius limits for the model as set by the user.
void setModelConstraints (std::function< bool(const Eigen::VectorXf &)> function)
This can be used to impose any kind of constraint on the model, e.g.
void setSamplesMaxDist (const double &radius, SearchPtr search)
Set the maximum distance allowed when drawing random samples.
void getSamplesMaxDist (double &radius) const
Get maximum distance allowed when drawing random samples.
double computeVariance (const std::vector< double > &error_sqr_dists) const
Compute the variance of the errors to the model.
double computeVariance () const
Compute the variance of the errors to the model from the internally estimated vector of distances.
Protected Member Functions
std::size_t countWithinDistanceStandard (const Eigen::VectorXf &model_coefficients, const double threshold, std::size_t i=0) const
This implementation uses no SIMD instructions.
Protected Member Functions inherited from pcl::SampleConsensusModel< PointT >
SampleConsensusModel (bool random=false)
Empty constructor for base SampleConsensusModel.
void drawIndexSample (Indices &sample)
Fills a sample array with random samples from the indices_ vector.
void drawIndexSampleRadius (Indices &sample)
Fills a sample array with one random sample from the indices_ vector and other random samples that are closer than samples_radius_.
virtual bool isModelValid (const Eigen::VectorXf &model_coefficients) const
Check whether a model is valid given the user constraints.
int rnd ()
Boost-based random number generator.
Additional Inherited Members
Protected Attributes inherited from pcl::SampleConsensusModel< PointT >
std::string model_name_
The model name.
PointCloudConstPtr input_
A boost shared pointer to the point cloud data array.
IndicesPtr indices_
A pointer to the vector of point indices to use.
double radius_min_
The minimum and maximum radius limits for the model.
double radius_max_
double samples_radius_
The maximum distance of subsequent samples from the first (radius search)
SearchPtr samples_radius_search_
The search object for picking subsequent samples using radius search.
Indices shuffled_indices_
Data containing a shuffled version of the indices.
boost::mt19937 rng_alg_
Boost-based random number generator algorithm.
std::shared_ptr< boost::uniform_int<> > rng_dist_
Boost-based random number generator distribution.
std::shared_ptr< boost::variate_generator< boost::mt19937 &, boost::uniform_int<> > > rng_gen_
Boost-based random number generator.
std::vector< double > error_sqr_dists_
A vector holding the distances to the computed model.
unsigned int sample_size_
The size of a sample from which the model is computed.
unsigned int model_size_
The number of coefficients in the model.
std::function< bool(const Eigen::VectorXf &)> custom_model_constraints_
A user defined function that takes model coefficients and returns whether the model is acceptable or not.
Static Protected Attributes inherited from pcl::SampleConsensusModel< PointT >
static const unsigned int max_sample_checks_ = 1000
The maximum number of samples to try until we get a good one.
Detailed Description
template<typename PointT>
class pcl::SampleConsensusModelPlane< PointT >
SampleConsensusModelPlane defines a model for 3D plane segmentation.
The model coefficients are defined as:
a : the X coordinate of the plane's normal (normalized)
b : the Y coordinate of the plane's normal (normalized)
c : the Z coordinate of the plane's normal (normalized)
d : the fourth Hessian component of the plane's equation
Author
Radu B. Rusu
Definition at line 142 of file sac_model_plane.h.
Member Typedef Documentation
ConstPtr
template<typename PointT > using pcl::SampleConsensusModelPlane< PointT >::ConstPtr = shared_ptr<const SampleConsensusModelPlane<PointT> >
Definition at line 156 of file sac_model_plane.h.
PointCloud
template<typename PointT > using pcl::SampleConsensusModelPlane< PointT >::PointCloud = typename SampleConsensusModel<PointT>::PointCloud
Definition at line 151 of file sac_model_plane.h.
PointCloudConstPtr
template<typename PointT > using pcl::SampleConsensusModelPlane< PointT >::PointCloudConstPtr = typename SampleConsensusModel<PointT>::PointCloudConstPtr
Definition at line 153 of file sac_model_plane.h.
PointCloudPtr
template<typename PointT > using pcl::SampleConsensusModelPlane< PointT >::PointCloudPtr = typename SampleConsensusModel<PointT>::PointCloudPtr
Definition at line 152 of file sac_model_plane.h.
Ptr
template<typename PointT > using pcl::SampleConsensusModelPlane< PointT >::Ptr = shared_ptr<SampleConsensusModelPlane<PointT> >
Definition at line 155 of file sac_model_plane.h.
Constructor & Destructor Documentation
SampleConsensusModelPlane() [1/2]
template<typename PointT > pcl::SampleConsensusModelPlane< PointT >::SampleConsensusModelPlane (const PointCloudConstPtr & cloud, bool random = false) inline
Constructor for base SampleConsensusModelPlane.
Parameters
[in] cloud the input point cloud dataset
[in] random if true set the random seed to the current time, else set to 12345 (default: false)
Definition at line 162 of file sac_model_plane.h.
References pcl::SampleConsensusModel< PointT >::model_name_, pcl::SampleConsensusModel< PointT >::model_size_, and pcl::SampleConsensusModel< PointT >::sample_size_.
SampleConsensusModelPlane() [2/2]
template<typename PointT > pcl::SampleConsensusModelPlane< PointT >::SampleConsensusModelPlane (const PointCloudConstPtr & cloud, const Indices & indices, bool random = false) inline
Constructor for base SampleConsensusModelPlane.
Parameters
[in] cloud the input point cloud dataset
[in] indices a vector of point indices to be used from cloud
[in] random if true set the random seed to the current time, else set to 12345 (default: false)
Definition at line 175 of file sac_model_plane.h.
References pcl::SampleConsensusModel< PointT >::model_name_, pcl::SampleConsensusModel< PointT >::model_size_, and pcl::SampleConsensusModel< PointT >::sample_size_.
~SampleConsensusModelPlane()
template<typename PointT > pcl::SampleConsensusModelPlane< PointT >::~SampleConsensusModelPlane () inline
Empty destructor.
Definition at line 186 of file sac_model_plane.h.
Member Function Documentation
computeModelCoefficients()
template<typename PointT > bool pcl::SampleConsensusModelPlane< PointT >::computeModelCoefficients (const Indices & samples, Eigen::VectorXf & model_coefficients) const override virtual
Check whether the given index samples can form a valid plane model, compute the model coefficients from these samples and store them internally in model_coefficients_.
The plane coefficients are: a, b, c, d (ax+by+cz+d=0)
Parameters
[in] samples the point indices found as possible good candidates for creating a valid model
[out] model_coefficients the resultant model coefficients
Implements pcl::SampleConsensusModel< PointT >.
Definition at line 70 of file sac_model_plane.hpp.
Referenced by pcl::registration::FPCSInitialAlignment< PointSource, PointTarget, pcl::Normal, float >::selectBase().
countWithinDistance()
template<typename PointT > std::size_t pcl::SampleConsensusModelPlane< PointT >::countWithinDistance (const Eigen::VectorXf & model_coefficients, const double threshold) const override virtual
Count all the points which respect the given model coefficients as inliers.
Parameters
[in] model_coefficients the coefficients of a model that we need to compute distances to
[in] threshold maximum admissible distance threshold for determining the inliers from the outliers
Returns
the resultant number of inliers
Implements pcl::SampleConsensusModel< PointT >.
Definition at line 216 of file sac_model_plane.hpp.
countWithinDistanceStandard()
template<typename PointT > std::size_t pcl::SampleConsensusModelPlane< PointT >::countWithinDistanceStandard (const Eigen::VectorXf & model_coefficients, const double threshold, std::size_t i = 0) const protected
This implementation uses no SIMD instructions.
It is not intended for normal use. See countWithinDistance which automatically uses the fastest implementation.
Definition at line 236 of file sac_model_plane.hpp.
doSamplesVerifyModel()
template<typename PointT > bool pcl::SampleConsensusModelPlane< PointT >::doSamplesVerifyModel (const std::set< index_t > & indices, const Eigen::VectorXf & model_coefficients, const double threshold) const override virtual
Verify whether a subset of indices verifies the given plane model coefficients.
Parameters
[in] indices the data indices that need to be tested against the plane model
[in] model_coefficients the plane model coefficients
[in] threshold a maximum admissible distance threshold for determining the inliers from the outliers
Implements pcl::SampleConsensusModel< PointT >.
Definition at line 472 of file sac_model_plane.hpp.
getDistancesToModel()
template<typename PointT > void pcl::SampleConsensusModelPlane< PointT >::getDistancesToModel (const Eigen::VectorXf & model_coefficients, std::vector< double > & distances) const override virtual
Compute all distances from the cloud data to a given plane model.
Parameters
[in] model_coefficients the coefficients of a plane model that we need to compute distances to
[out] distances the resultant estimated distances
Implements pcl::SampleConsensusModel< PointT >.
Definition at line 147 of file sac_model_plane.hpp.
getModelType()
template<typename PointT > pcl::SacModel pcl::SampleConsensusModelPlane< PointT >::getModelType () const inline override virtual
Return a unique id for this model (SACMODEL_PLANE).
Implements pcl::SampleConsensusModel< PointT >.
Definition at line 261 of file sac_model_plane.h.
References pcl::SACMODEL_PLANE.
optimizeModelCoefficients()
template<typename PointT > void pcl::SampleConsensusModelPlane< PointT >::optimizeModelCoefficients (const Indices & inliers, const Eigen::VectorXf & model_coefficients, Eigen::VectorXf & optimized_coefficients) const override virtual
Recompute the plane coefficients using the given inlier set and return them to the user.
Note
: these are the coefficients of the plane model after refinement (e.g. after SVD)
Parameters
[in] inliers the data inliers found as supporting the model
[in] model_coefficients the initial guess for the model coefficients
[out] optimized_coefficients the resultant recomputed coefficients after non-linear optimization
Implements pcl::SampleConsensusModel< PointT >.
Definition at line 337 of file sac_model_plane.hpp.
References pcl::computeMeanAndCovarianceMatrix(), and pcl::eigen33().
Referenced by pcl::people::GroundBasedPeopleDetectionApp< PointT >::compute().
projectPoints()
template<typename PointT > void pcl::SampleConsensusModelPlane< PointT >::projectPoints (const Indices & inliers, const Eigen::VectorXf & model_coefficients, PointCloud & projected_points, bool copy_data_fields = true) const override virtual
Create a new point cloud with inliers projected onto the plane model.
Parameters
[in] inliers the data inliers that we want to project on the plane model
[in] model_coefficients the normalized coefficients of a plane model
[out] projected_points the resultant projected points
[in] copy_data_fields set to true if we need to copy the other data fields
Implements pcl::SampleConsensusModel< PointT >.
Definition at line 386 of file sac_model_plane.hpp.
References pcl::PointCloud< PointT >::header, pcl::PointCloud< PointT >::height, pcl::PointCloud< PointT >::is_dense, pcl::PointCloud< PointT >::resize(), and pcl::PointCloud< PointT >::width.
Referenced by pcl::ExtractPolygonalPrismData< PointT >::segment().
selectWithinDistance()
template<typename PointT > void pcl::SampleConsensusModelPlane< PointT >::selectWithinDistance (const Eigen::VectorXf & model_coefficients, const double threshold, Indices & inliers) override virtual
Select all the points which respect the given model coefficients as inliers.
Parameters
[in] model_coefficients the coefficients of a plane model that we need to compute distances to
[in] threshold a maximum admissible distance threshold for determining the inliers from the outliers
[out] inliers the resultant model inliers
Implements pcl::SampleConsensusModel< PointT >.
Definition at line 178 of file sac_model_plane.hpp.
References pcl::geometry::distance().
Referenced by pcl::people::GroundBasedPeopleDetectionApp< PointT >::compute().
The documentation for this class was generated from the following files:
pcl/sample_consensus/sac_model_plane.h
pcl/sample_consensus/impl/sac_model_plane.hpp
20092012, Willow Garage, Inc.
2012, Open Perception, Inc.
Licensed under the BSD License.
https://pointclouds.org/documentation/classpcl_1_1_sample_consensus_model_plane.html