pcl::EventFrequency Class ReferenceModule Common - PointCloudLibrary - W3cubDocs
W3cubDocs
/PointCloudLibrary
A helper class to measure frequency of a certain event.
#include <pcl/common/time.h>
Public Member Functions
EventFrequency (std::size_t window_size=30)
Constructor.
void event ()
Notifies the class that the event occurred.
double getFrequency () const
Retrieve the estimated frequency.
void reset ()
Reset frequency computation.
Detailed Description
A helper class to measure frequency of a certain event.
To use this class create an instance and call event() function every time the event in question occurs. The estimated frequency can be retrieved with getFrequency() function.
Author
Sergey Alexandrov
Definition at line 134 of file time.h.
Constructor & Destructor Documentation
EventFrequency()
pcl::EventFrequency::EventFrequency (std::size_t window_size = 30) inline
Constructor.
Parameters
[in] window_size number of most recent events that are considered in frequency estimation (default: 30)
Definition at line 143 of file time.h.
References pcl::StopWatch::reset().
Member Function Documentation
event()
void pcl::EventFrequency::event () inline
Notifies the class that the event occurred.
Definition at line 150 of file time.h.
References pcl::StopWatch::getTimeSeconds().
getFrequency()
double pcl::EventFrequency::getFrequency () const inline
Retrieve the estimated frequency.
Definition at line 159 of file time.h.
reset()
void pcl::EventFrequency::reset () inline
Reset frequency computation.
Definition at line 168 of file time.h.
References pcl::StopWatch::reset().
The documentation for this class was generated from the following file:
pcl/common/time.h
© 2009–2012, Willow Garage, Inc.
© 2012–, Open Perception, Inc.
Licensed under the BSD License.
https://pointclouds.org/documentation/classpcl_1_1_event_frequency.html