pcl::DistanceMap Class Reference - PointCloudLibrary - W3cubDocs
W3cubDocs
/PointCloudLibrary
Represents a distance map obtained from a distance transformation.
#include <pcl/recognition/distance_map.h>
Public Member Functions
DistanceMap ()
Constructor.
virtual ~DistanceMap ()
Destructor.
std::size_t getWidth () const
Returns the width of the map.
std::size_t getHeight () const
Returns the height of the map.
float * getData ()
Returns a pointer to the beginning of map.
void resize (const std::size_t width, const std::size_t height)
Resizes the map to the specified size.
float & operator() (const std::size_t col_index, const std::size_t row_index)
Operator to access an element of the map.
const float & operator() (const std::size_t col_index, const std::size_t row_index) const
Operator to access an element of the map.
Protected Attributes
std::vector< float > data_
The storage for the distance map data.
std::size_t width_
The width of the map.
std::size_t height_
The height of the map.
Detailed Description
Represents a distance map obtained from a distance transformation.
Author
Stefan Holzer
Definition at line 46 of file distance_map.h.
Constructor & Destructor Documentation
DistanceMap()
pcl::DistanceMap::DistanceMap () inline
Constructor.
Definition at line 50 of file distance_map.h.
~DistanceMap()
virtual pcl::DistanceMap::~DistanceMap () inline virtual
Destructor.
Definition at line 52 of file distance_map.h.
Member Function Documentation
getData()
float* pcl::DistanceMap::getData () inline
Returns a pointer to the beginning of map.
Definition at line 70 of file distance_map.h.
References data_.
Referenced by pcl::ColorModality< PointInT >::computeDistanceMap(), and pcl::SurfaceNormalModality< PointXYZT >::computeDistanceMap().
getHeight()
std::size_t pcl::DistanceMap::getHeight () const inline
Returns the height of the map.
Definition at line 63 of file distance_map.h.
References height_.
getWidth()
std::size_t pcl::DistanceMap::getWidth () const inline
Returns the width of the map.
Definition at line 56 of file distance_map.h.
References width_.
operator()() [1/2]
float& pcl::DistanceMap::operator() (const std::size_t col_index, const std::size_t row_index) inline
Operator to access an element of the map.
Parameters
[in] col_index the column index of the element to access.
[in] row_index the row index of the element to access.
Definition at line 92 of file distance_map.h.
References data_, and width_.
operator()() [2/2]
const float& pcl::DistanceMap::operator() (const std::size_t col_index, const std::size_t row_index) const inline
Operator to access an element of the map.
Parameters
[in] col_index the column index of the element to access.
[in] row_index the row index of the element to access.
Definition at line 102 of file distance_map.h.
References data_, and width_.
resize()
void pcl::DistanceMap::resize (const std::size_t width, const std::size_t height) inline
Resizes the map to the specified size.
Parameters
[in] width the new width of the map.
[in] height the new height of the map.
Definition at line 80 of file distance_map.h.
References data_, height_, and width_.
Referenced by pcl::ColorModality< PointInT >::computeDistanceMap(), and pcl::SurfaceNormalModality< PointXYZT >::computeDistanceMap().
Member Data Documentation
data_
std::vector<float> pcl::DistanceMap::data_ protected
The storage for the distance map data.
Definition at line 109 of file distance_map.h.
Referenced by getData(), operator()(), and resize().
height_
std::size_t pcl::DistanceMap::height_ protected
The height of the map.
Definition at line 113 of file distance_map.h.
Referenced by getHeight(), and resize().
width_
std::size_t pcl::DistanceMap::width_ protected
The width of the map.
Definition at line 111 of file distance_map.h.
Referenced by getWidth(), operator()(), and resize().
The documentation for this class was generated from the following file:
pcl/recognition/distance_map.h
© 2009–2012, Willow Garage, Inc.
© 2012–, Open Perception, Inc.
Licensed under the BSD License.
https://pointclouds.org/documentation/classpcl_1_1_distance_map.html