pcl::octree::OctreeNode Class Referenceabstract - PointCloudLibrary - W3cubDocs
W3cubDocs
/PointCloudLibrary
Abstract octree node class
#include <pcl/octree/octree_nodes.h>
Public Member Functions
OctreeNode ()
virtual ~OctreeNode ()
virtual node_type_t getNodeType () const =0
Pure virtual method for receiving the type of octree node (branch or leaf)
virtual OctreeNode * deepCopy () const =0
Pure virtual method to perform a deep copy of the octree.
Detailed Description
Abstract octree node class
Note
Every octree node should implement the getNodeType () method
Author
Julius Kammerl (juliu.nosp@m.s@ka.nosp@m.mmerl.nosp@m..de)
Definition at line 58 of file octree_nodes.h.
Constructor & Destructor Documentation
OctreeNode()
pcl::octree::OctreeNode::OctreeNode () inline
Definition at line 60 of file octree_nodes.h.
~OctreeNode()
virtual pcl::octree::OctreeNode::~OctreeNode () inline virtual
Definition at line 62 of file octree_nodes.h.
Member Function Documentation
deepCopy()
virtual OctreeNode* pcl::octree::OctreeNode::deepCopy () const pure virtual
Pure virtual method to perform a deep copy of the octree.
Implemented in pcl::octree::OctreeBranchNode< ContainerT >, pcl::octree::OctreeLeafNode< ContainerT >, and pcl::octree::BufferedBranchNode< ContainerT >.
Referenced by pcl::octree::OctreeBranchNode< ContainerT >::OctreeBranchNode(), pcl::octree::BufferedBranchNode< ContainerT >::operator=(), and pcl::octree::OctreeBranchNode< ContainerT >::operator=().
getNodeType()
virtual node_type_t pcl::octree::OctreeNode::getNodeType () const pure virtual
Pure virtual method for receiving the type of octree node (branch or leaf)
Implemented in pcl::octree::OctreeBranchNode< ContainerT >, pcl::octree::BufferedBranchNode< ContainerT >, and pcl::octree::OctreeLeafNode< ContainerT >.
Referenced by pcl::octree::OctreePointCloudSearch< PointT, pcl::octree::OctreeContainerPointIndices, pcl::octree::OctreeContainerEmpty >::approxNearestSearchRecursive(), pcl::octree::OctreePointCloudSearch< PointT, pcl::octree::OctreeContainerPointIndices, pcl::octree::OctreeContainerEmpty >::boxSearchRecursive(), pcl::octree::OctreeBase< OctreePointCloudVoxelCentroidContainer< PointT >, OctreeContainerEmpty >::createLeafRecursive(), pcl::octree::Octree2BufBase< OctreeContainerPointIndices, OctreeContainerEmpty >::createLeafRecursive(), pcl::octree::OctreeBase< OctreePointCloudVoxelCentroidContainer< PointT >, OctreeContainerEmpty >::deleteBranchChild(), pcl::octree::Octree2BufBase< OctreeContainerPointIndices, OctreeContainerEmpty >::deleteBranchChild(), pcl::octree::OctreeBase< OctreePointCloudVoxelCentroidContainer< PointT >, OctreeContainerEmpty >::deleteLeafRecursive(), pcl::octree::Octree2BufBase< OctreeContainerPointIndices, OctreeContainerEmpty >::deserializeTreeRecursive(), pcl::octree::OctreeBase< OctreePointCloudVoxelCentroidContainer< PointT >, OctreeContainerEmpty >::findLeafRecursive(), pcl::octree::OctreePointCloudSearch< PointT, pcl::octree::OctreeContainerPointIndices, pcl::octree::OctreeContainerEmpty >::getIntersectedVoxelCentersRecursive(), pcl::octree::OctreePointCloudSearch< PointT, pcl::octree::OctreeContainerPointIndices, pcl::octree::OctreeContainerEmpty >::getIntersectedVoxelIndicesRecursive(), pcl::octree::OctreePointCloudSearch< PointT, pcl::octree::OctreeContainerPointIndices, pcl::octree::OctreeContainerEmpty >::getKNearestNeighborRecursive(), pcl::octree::OctreePointCloudSearch< PointT, pcl::octree::OctreeContainerPointIndices, pcl::octree::OctreeContainerEmpty >::getNeighborsWithinRadiusRecursive(), pcl::octree::OctreePointCloud< PointT, OctreeContainerPointIndex, OctreeContainerEmpty, OctreeBase< OctreeContainerPointIndex, OctreeContainerEmpty > >::getOccupiedVoxelCentersRecursive(), pcl::octree::OctreePointCloudVoxelCentroid< PointT, LeafContainerT, BranchContainerT >::getVoxelCentroidsRecursive(), pcl::octree::OctreeIteratorBase< OctreeT >::isBranchNode(), pcl::octree::OctreeIteratorBase< OctreeT >::isLeafNode(), pcl::octree::OctreeLeafNodeDepthFirstIterator< OctreeT >::operator*(), pcl::octree::OctreeDepthFirstIterator< OctreeT >::operator++(), pcl::octree::OctreeBreadthFirstIterator< OctreeT >::operator++(), pcl::octree::OctreeLeafNodeDepthFirstIterator< OctreeT >::operator++(), pcl::octree::OctreeBase< OctreePointCloudVoxelCentroidContainer< PointT >, OctreeContainerEmpty >::serializeTreeRecursive(), pcl::octree::Octree2BufBase< OctreeContainerPointIndices, OctreeContainerEmpty >::serializeTreeRecursive(), and pcl::octree::Octree2BufBase< OctreeContainerPointIndices, OctreeContainerEmpty >::treeCleanUpRecursive().
The documentation for this class was generated from the following file:
pcl/octree/octree_nodes.h
© 2009–2012, Willow Garage, Inc.
© 2012–, Open Perception, Inc.
Licensed under the BSD License.
https://pointclouds.org/documentation/classpcl_1_1octree_1_1_octree_node.html