pcl::io::LZFDepth16ImageReader Class ReferenceModule Io - PointCloudLibrary - W3cubDocs
W3cubDocs
/PointCloudLibrary
PCL-LZF 16-bit depth image format reader.
#include <pcl/io/lzf_image_io.h>
Public Member Functions
LZFDepth16ImageReader ()
Empty constructor.
~LZFDepth16ImageReader ()
Empty destructor.
template<typename PointT >
bool read (const std::string &filename, pcl::PointCloud< PointT > &cloud)
Read the data stored in a PCLZF depth file and convert it to a pcl::PointCloud type.
template<typename PointT >
bool readOMP (const std::string &filename, pcl::PointCloud< PointT > &cloud, unsigned int num_threads=0)
Read the data stored in a PCLZF depth file and convert it to a pcl::PointCloud type.
bool readParameters (std::istream &is) override
Read camera parameters from a given stream and store them internally.
bool readParameters (const std::string &filename)
Read camera parameters from a given file and store them internally.
virtual bool readParameters (std::istream &)
Read camera parameters from a given stream and store them internally.
Public Member Functions inherited from pcl::io::LZFImageReader
LZFImageReader ()
Empty constructor.
virtual ~LZFImageReader ()
Empty destructor.
bool readParameters (const std::string &filename)
Read camera parameters from a given file and store them internally.
void setParameters (const CameraParameters &parameters)
Read the parameters from a struct instead.
CameraParameters getParameters () const
Get the camera parameters currently being used returns a CameraParameters struct.
std::uint32_t getWidth () const
Get the image width as read from disk.
std::uint32_t getHeight () const
Get the image height as read from disk.
std::string getImageType () const
Get the type of the image read from disk.
Protected Attributes
double z_multiplication_factor_
Z-value depth multiplication factor (i.e., if raw data is in [mm] and we want [m], we need to multiply with 0.001)
Protected Attributes inherited from pcl::io::LZFImageReader
std::uint32_t width_
The image width, as read from the file.
std::uint32_t height_
The image height, as read from the file.
std::string image_type_identifier_
The image type string, as read from the file.
CameraParameters parameters_
Internal set of camera parameters.
Additional Inherited Members
Protected Member Functions inherited from pcl::io::LZFImageReader
bool loadImageBlob (const std::string &filename, std::vector< char > &data, std::uint32_t &uncompressed_size)
Load a compressed image array from disk.
bool decompress (const std::vector< char > &input, std::vector< char > &output)
Realtime LZF decompression.
Detailed Description
PCL-LZF 16-bit depth image format reader.
The main advantage of using the PCL-LZF image I/O routines is a very good file size versus I/O speed ratio. Tests performed using LZF, Snappy, ZIP, GZ2, BZIP2, as well as PNG, JPEG, and TIFF compression have shown that the internal PCL LZF methods provide the best score for the types of applications PCL is suited for.
Author
Radu B. Rusu
Definition at line 186 of file lzf_image_io.h.
Constructor & Destructor Documentation
LZFDepth16ImageReader()
pcl::io::LZFDepth16ImageReader::LZFDepth16ImageReader () inline
Empty constructor.
Definition at line 192 of file lzf_image_io.h.
~LZFDepth16ImageReader()
pcl::io::LZFDepth16ImageReader::~LZFDepth16ImageReader () inline
Empty destructor.
Definition at line 197 of file lzf_image_io.h.
Member Function Documentation
read()
template<typename PointT > bool pcl::io::LZFDepth16ImageReader::read (const std::string & filename, pcl::PointCloud< PointT > & cloud)
Read the data stored in a PCLZF depth file and convert it to a pcl::PointCloud type.
Parameters
[in] filename the file name to read the data from
[out] cloud the resultant output point cloud
Definition at line 61 of file lzf_image_io.hpp.
References pcl::io::LZFImageReader::decompress(), pcl::io::CameraParameters::focal_length_x, pcl::io::CameraParameters::focal_length_y, pcl::io::LZFImageReader::getHeight(), pcl::io::LZFImageReader::getImageType(), pcl::io::LZFImageReader::getWidth(), pcl::PointCloud< PointT >::height, pcl::PointCloud< PointT >::is_dense, pcl::io::LZFImageReader::loadImageBlob(), pcl::io::LZFImageReader::parameters_, pcl::io::CameraParameters::principal_point_x, pcl::io::CameraParameters::principal_point_y, pcl::PointCloud< PointT >::resize(), pcl::PointCloud< PointT >::sensor_orientation_, pcl::PointCloud< PointT >::sensor_origin_, pcl::PointCloud< PointT >::width, and z_multiplication_factor_.
readOMP()
template<typename PointT > bool pcl::io::LZFDepth16ImageReader::readOMP (const std::string & filename, pcl::PointCloud< PointT > & cloud, unsigned int num_threads = 0)
Read the data stored in a PCLZF depth file and convert it to a pcl::PointCloud type.
Parameters
[in] filename the file name to read the data from
[in] num_threads The number of threads to use. 0 indicates OpenMP is free to choose.
[out] cloud the resultant output point cloud
Definition at line 126 of file lzf_image_io.hpp.
References pcl::io::LZFImageReader::decompress(), pcl::io::CameraParameters::focal_length_x, pcl::io::CameraParameters::focal_length_y, pcl::io::LZFImageReader::getHeight(), pcl::io::LZFImageReader::getImageType(), pcl::io::LZFImageReader::getWidth(), pcl::PointCloud< PointT >::height, pcl::utils::ignore(), pcl::PointCloud< PointT >::is_dense, pcl::io::LZFImageReader::loadImageBlob(), pcl::io::LZFImageReader::parameters_, pcl::io::CameraParameters::principal_point_x, pcl::io::CameraParameters::principal_point_y, pcl::PointCloud< PointT >::resize(), pcl::PointCloud< PointT >::sensor_orientation_, pcl::PointCloud< PointT >::sensor_origin_, pcl::PointCloud< PointT >::size(), pcl::PointCloud< PointT >::width, and z_multiplication_factor_.
readParameters() [1/3]
bool pcl::io::LZFImageReader::readParameters
Read camera parameters from a given file and store them internally.
Returns
true if operation successful, false otherwise
readParameters() [2/3]
virtual bool pcl::io::LZFImageReader::readParameters inline
Read camera parameters from a given stream and store them internally.
Returns
true if operation successful, false otherwise
Definition at line 141 of file lzf_image_io.h.
readParameters() [3/3]
bool pcl::io::LZFDepth16ImageReader::readParameters (std::istream & is) override virtual
Read camera parameters from a given stream and store them internally.
The parameters will be read from the <depth> ... </depth> tag.
Returns
true if operation successful, false otherwise
Reimplemented from pcl::io::LZFImageReader.
Member Data Documentation
z_multiplication_factor_
double pcl::io::LZFDepth16ImageReader::z_multiplication_factor_ protected
Z-value depth multiplication factor (i.e., if raw data is in [mm] and we want [m], we need to multiply with 0.001)
Definition at line 226 of file lzf_image_io.h.
Referenced by read(), and readOMP().
The documentation for this class was generated from the following files:
pcl/io/lzf_image_io.h
pcl/io/impl/lzf_image_io.hpp
© 2009–2012, Willow Garage, Inc.
© 2012–, Open Perception, Inc.
Licensed under the BSD License.
https://pointclouds.org/documentation/classpcl_1_1io_1_1_l_z_f_depth16_image_reader.html